codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1 # 1つのビルド後に通知

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 10%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files" # filesを追加してファイル別表示
  behavior: default
  require_changes: no
  require_base: no # ベースブランチのカバレッジがなくてもコメント可能
  require_head: yes # HEADブランチのカバレッジは必須

ignore:
  - "tests/**/*"
  - "**/test_*.py"
  - "**/__pycache__"
  - "**/.pytest_cache"
  - "scripts/**/*" # スクリプトファイルも除外（必要に応じて）
